#!/bin/bash

### EDIT THESE VALUES #########################################################
APP="env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/slack_slack.desktop /snap/bin/slack %U"      # path to real executable
ICON="/snap/slack/current/usr/share/pixmaps/slack.png"    	  # icon file - only png supported
WAIT=20                			  # wait time for application window to display - adjust to suit
###############################################################################

###############################################################################
### DON'T CHANGE ANYTHING BELOW
###############################################################################
function change-panel-icon {

    sleep $WAIT
    activeWinLine=$(xprop -root | grep "_NET_ACTIVE_WINDOW(WINDOW)")
    activeWinId="${activeWinLine:40}"

    xseticon -id "$activeWinId" "$ICON"
    xprop -id "$activeWinId" -f _NET_WM_WINDOW_TYPE 32a -set _NET_WM_WINDOW_TYPE _NET_WM_WINDOW_TYPE_NORMAL
}

$APP & change-panel-icon
